import { QueryClient } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
// Auto-generated by @tanstack/router-plugin (bundled inside tanstackStart())
// the first time `vite dev` / `vite build` runs — not present until then.
import { routeTree } from "./routeTree.gen";

export const getRouter = () => {
  const queryClient = new QueryClient();

  const router = createRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
  });

  return router;
};
